---

- hosts: wg_server
  vars_files:
    - 'vars/vault.yaml'
  tasks:
  - name: Update apt-get repo and cache
    apt: update_cache=yes
  - name: Upgrade all apt packages
    apt: upgrade=dist
  - name: install packages
    package:
      name: "{{ item }}"
      state: present
    loop:
      - wireguard
  - name: config packet forwarding and proxy_arp
    lineinfile:
      path: "/etc/sysctl.conf"
      regexp: '^{{item}}'
      line: '{{item}} = 1'
    loop:
      - net.ipv4.ip_forward
      - net.ipv4.conf.all.proxy_arp
  - name: create config for wg server
    template:
      src: "server_wg0.conf.j2"
      dest: "/etc/wireguard/wg0.conf"
  - name: commands
    command: "{{item}}"
    loop:
      - sysctl -p  # loads the edits from sysctl.conf
      - systemctl enable wg-quick@wg0
      - systemctl start wg-quick@wg0
      - shutdown -r 1 # reboot in 1 minute
  roles:
    - role: jnv.unattended-upgrades

- hosts: wg_client
  tags: client
  vars_files:
    - 'vars/vault.yaml'
  tasks:
  - name: create config for wg# peer1
    template:
      src: "peer1_wg0.conf.j2"
      dest: "peer1_{{ inventory_hostname }}.conf"
  - name: create config for wg# peer2
    template:
      src: "peer2_wg0.conf.j2"
      dest: "peer2_{{ inventory_hostname }}.conf"